Default: &defaults
  database: Cool.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: Cool_test.sqlite3
  <<: *defaults

Staging:
  database: Cool_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: Cool_production.sqlite3
  poolsize: 100
  <<: *defaults
